/* tslint:disable */
/* eslint-disable */
/**
 * OpenWeather One Call API
 * OpenWeather One Call API 3.0 for comprehensive weather data
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DailyForecastFeelsLike
 */
export interface DailyForecastFeelsLike {
    /**
     * 
     * @type {number}
     * @memberof DailyForecastFeelsLike
     */
    day?: number;
    /**
     * 
     * @type {number}
     * @memberof DailyForecastFeelsLike
     */
    night?: number;
    /**
     * 
     * @type {number}
     * @memberof DailyForecastFeelsLike
     */
    eve?: number;
    /**
     * 
     * @type {number}
     * @memberof DailyForecastFeelsLike
     */
    morn?: number;
}

/**
 * Check if a given object implements the DailyForecastFeelsLike interface.
 */
export function instanceOfDailyForecastFeelsLike(value: object): value is DailyForecastFeelsLike {
    return true;
}

export function DailyForecastFeelsLikeFromJSON(json: any): DailyForecastFeelsLike {
    return DailyForecastFeelsLikeFromJSONTyped(json, false);
}

export function DailyForecastFeelsLikeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DailyForecastFeelsLike {
    if (json == null) {
        return json;
    }
    return {
        
        'day': json['day'] == null ? undefined : json['day'],
        'night': json['night'] == null ? undefined : json['night'],
        'eve': json['eve'] == null ? undefined : json['eve'],
        'morn': json['morn'] == null ? undefined : json['morn'],
    };
}

  export function DailyForecastFeelsLikeToJSON(json: any): DailyForecastFeelsLike {
      return DailyForecastFeelsLikeToJSONTyped(json, false);
  }

  export function DailyForecastFeelsLikeToJSONTyped(value?: DailyForecastFeelsLike | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'day': value['day'],
        'night': value['night'],
        'eve': value['eve'],
        'morn': value['morn'],
    };
}

