/* tslint:disable */
/* eslint-disable */
/**
 * OpenWeather One Call API
 * OpenWeather One Call API 3.0 for comprehensive weather data
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CurrentWeather } from './CurrentWeather';
import {
    CurrentWeatherFromJSON,
    CurrentWeatherFromJSONTyped,
    CurrentWeatherToJSON,
    CurrentWeatherToJSONTyped,
} from './CurrentWeather';
import type { DailyForecast } from './DailyForecast';
import {
    DailyForecastFromJSON,
    DailyForecastFromJSONTyped,
    DailyForecastToJSON,
    DailyForecastToJSONTyped,
} from './DailyForecast';

/**
 * 
 * @export
 * @interface OnecallClimateGet200Response
 */
export interface OnecallClimateGet200Response {
    /**
     * AI-generated weather summary
     * @type {string}
     * @memberof OnecallClimateGet200Response
     */
    summary?: string;
    /**
     * 
     * @type {CurrentWeather}
     * @memberof OnecallClimateGet200Response
     */
    current?: CurrentWeather;
    /**
     * 
     * @type {DailyForecast}
     * @memberof OnecallClimateGet200Response
     */
    tomorrow?: DailyForecast;
}

/**
 * Check if a given object implements the OnecallClimateGet200Response interface.
 */
export function instanceOfOnecallClimateGet200Response(value: object): value is OnecallClimateGet200Response {
    return true;
}

export function OnecallClimateGet200ResponseFromJSON(json: any): OnecallClimateGet200Response {
    return OnecallClimateGet200ResponseFromJSONTyped(json, false);
}

export function OnecallClimateGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OnecallClimateGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'summary': json['summary'] == null ? undefined : json['summary'],
        'current': json['current'] == null ? undefined : CurrentWeatherFromJSON(json['current']),
        'tomorrow': json['tomorrow'] == null ? undefined : DailyForecastFromJSON(json['tomorrow']),
    };
}

  export function OnecallClimateGet200ResponseToJSON(json: any): OnecallClimateGet200Response {
      return OnecallClimateGet200ResponseToJSONTyped(json, false);
  }

  export function OnecallClimateGet200ResponseToJSONTyped(value?: OnecallClimateGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'summary': value['summary'],
        'current': CurrentWeatherToJSON(value['current']),
        'tomorrow': DailyForecastToJSON(value['tomorrow']),
    };
}

